### ISSUE TITLE
对于显卡型号有要求吗

### ISSUE THREAD

**Issue by yangdatianxia** [zrsolis/vgpu-openstack#1]
hello，我想问一下，您当时有没有买vgpus得授权，还有就是，您得openstack这玩意是分配vgpu得时候是按照cuda核心数进行分配还是按照显存进行分配啊

**Comment by zrsolis** [comment]
When I set this up I was doing the 90-day trial of the GRID licensing. For the profiles, the allocation is based on pre-defined profiles that are based on the type of workload (i.e. virtual workstation, compute, etc.) and video memory. You can find the profiles in the NVidia GRID User Guide: https://docs.nvidia.com/grid/16.0/grid-vgpu-user-guide/index.html
